### ISSUE TITLE
Opentelemetry implementation for AKS

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/solutions#125]
Deploy grafana & jaeger with quarkus application using helm chart.

**Comment by sujith-mn** [comment]
an example
https://docs.microsoft.com/en-us/azure/aks/ingress-own-tls?tabs=azure-cli

**Comment by sujith-mn** [comment]
Tried a possibility like URL rewrite, but it was not working. Adding grafana/jaeger as part of the url. But due to `nginx` related issues, dropped this plan.

The current solution is to create additional public ip address and configure subdomains and use.
