### ISSUE TITLE
Add preview to PRs

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/solutions#19]
As a PR creator, I want to see how my solution would look like before the PR is merged so I can see that everything looks like I want it to look.

Links that could be helpful:
https://www.npmjs.com/package/node-html-to-image
https://github.com/marketplace/actions/workflow-artifact-pull-request-comment

**Comment by SchettlerKoehler** [comment]
@AnneHrbrt @dolvie1012 @MarvDan @yF-B Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/New-UI-experience-60d339c7fb9a44000f6dff47/issues/devonfw/architectures/19?planning-poker)

**Comment by suprishi** [comment]
Rest 13
