### ISSUE TITLE
Introduction to the solution browser

### ISSUE THREAD

**Issue by maybeec** [devonfw/solutions#82]
As a reader, I want to get the best consulting about cloud solutions so that devonfw is a good starting point for me, but if needing different solutions, I would like to get more information about the vendors.

The following section should be shown as an introduction above the solution browser:

Below you will find carefully harvested and proposed standard solutions of devonfw. Their central purpose is to standardize on green-field solutions as well as to foster discussion on why to do things differently. Broadening your knowledge about cloud reference architectures and further solution ideas, you might want to take a look at the
[AWS Well-Architected Framework and its reference architectures](https://aws.amazon.com/en/architecture/) as well as the [Azure Well-Architected Framework](https://docs.microsoft.com/en-en/azure/architecture/framework/) and its [reference architectures](https://docs.microsoft.com/de-de/azure/architecture/browse/).

**Comment by SchettlerKoehler** [comment]
@tobka777 and @maybeec the change broke the layout.
@tobka777 can you please have a look at this?

**Comment by tobka777** [comment]
@SchettlerKoehler so I did some rework to use bootstrap classes for the grid layout and not absolute position. I hope that's not only worked on my machine ;).
